### ISSUE TITLE
Training bert model

### ISSUE THREAD

**Issue by emilienschultz** [emilienschultz/pyactivetigger#10]
Question @jboelaert : is there a reason why you implemented the bert training from transformer and not relied on the ASS wrapper https://github.com/rubingshen/AugmentedSocialScientist ? Would it be ok to use it to facilitate the code maintainability ?

(I can keep you code of course, I have no strong preference)

**Comment by jboelaert** [comment]
I don't really see the point of using the ASS wrapper, it seems to me that using transformers directly gives more flexibility and is easier to maintain (ASS depends on transformers anyway).

**Comment by emilienschultz** [comment]
yes, but since it builds abstraction, it could help to separate the evolution of the AT and the evolution of transformers and fine tuning optimisation.

For the moment I will stick to your code :)
