### ISSUE TITLE
chunking for bert prediction

### ISSUE THREAD

**Issue by emilienschultz** [emilienschultz/pyactivetigger#12]
The prediction is by chuncks. Why ? The possibility to predict directly on the whole dataset would be less efficient ? Or is it for progress bar ?

  chunks = chunker([str(x) for x in dat[args.txtname]], args.batch)
  pred = []
  for i, x in enumerate(chunks):
    if (i % 5 == 0):
      percent = round(100 * i * args.batch / len(dat), 1)
      logmsg = "Computing: " + str(percent) + "% (" + str(i * args.batch) + "/" + str(len(dat)) + ")"
      with open(path.expanduser(args.logfile), "w") as progfile:
        progfile.write(logmsg)
    pred.append(get_predprobs(x))

**Comment by jboelaert** [comment]
It's a question of inference speed: inference is much faster on minibatches (but too large minibatches can give CUDA OOM errors)

**Comment by emilienschultz** [comment]
ok, will keep your code then
