### ISSUE TITLE
calculate entropy

### ISSUE THREAD

**Issue by emilienschultz** [emilienschultz/pyactivetigger#27]
Hi Julien, 
where do you calculate the entropy of the bert prediction in your code. The formula is -sum(p_i*log(p_i)) ?
(still making progress, but slowly, but progress)
Thanks, 
Emilien

**Comment by jboelaert** [comment]
Hi Émilien,
yes indeed, that's the formula. It's not for Bert predictions though, but
for the simple model.
It's at line 1461 of server.R : tominimize <- rowSums(dapred * log(dapred))
Best
J

**Comment by emilienschultz** [comment]
Ho, I thought it was also for the bert ! sorry for the confusion.

**Comment by jboelaert** [comment]
Only insofar as the Bert predictions can enter the simple model
