### ISSUE TITLE
implement lasso model

### ISSUE THREAD

**Issue by emilienschultz** [emilienschultz/pyactivetigger#3]
Is it ok to use a logistic regression with L1 penalty for the lasso model ?

**Comment by jboelaert** [comment]
Absolutely, except that it's most likely a multinomial logistic regression. 
Lasso is just a fast algorithm to obtain L1 regression, which I would guess is the one they use in the implementations of L1 regression?

**Comment by emilienschultz** [comment]
I have the same guess, so I start with that. Thanks :)
