### ISSUE TITLE
"liblinear cost" meaning : is it the cost of a logistic regression ?

### ISSUE THREAD

**Issue by emilienschultz** [emilienschultz/pyactivetigger#6]
sklearn doc :

C (float), default=1.0

Inverse of regularization strength; must be a positive float. Like in support vector machines, smaller values specify stronger regularization.

If so, why 32 by default in active tigger ?

**Comment by jboelaert** [comment]
No particular reason for the 32 default, it just seemed to be a good baseline, based on empirical experimentation with LiblineaR's heuristicC function.

**Comment by emilienschultz** [comment]
ok :)

**Comment by emilienschultz** [comment]
I will use C = 32 for the moment
