### ISSUE TITLE
Attempt to manage auth

### ISSUE THREAD

**Issue by emilienschultz** [emilienschultz/pyactivetigger#64]
@paulgirard I made some attempt to manage the auth to have it on the front page and directly routing to the projects page. For the moment, it is in the branch *homepage* to review...

I was wondering how to deal with the Error throw when the username/password is not good. I used try/catch but not sure it is the way. + I would like to keep the error message from the API

**Comment by paulgirard** [comment]
Well I've been working on refactoing the auth system.. Your modifications are outdated.. sorry.
This being said we need to put a notification system in place to show errors like wrong login attempts.
I've just opened #65 and assigned it to me.
