### ISSUE TITLE
display current project in the NavBar

### ISSUE THREAD

**Issue by emilienschultz** [emilienschultz/pyactivetigger#70]
@paulgirard  : how to add the project name in the Nav Bar when selected ?

Do I create a projectContext in the NavBar component, with a useProjectParams, which is modified when selection of the project occure ?

**Comment by paulgirard** [comment]
No. The current project must be in the URL so you don't need any context.
For pages that are project specific they have to have a route nested under /project/[slug]/
Like for instance /project/[slug]/annotate

When you do that the AnnotatePage will receive the project slug as param using useParam

Actually all the components used by AnnotatePage can also use this hook.
So you can use the same useParam in the navbar to retrieve the current project slug. But you'll get only the slug.

If you want the label you can either get the label from the API in navbar or add a projectLabel props in the navbar which will be used by the AnnotatePage component who will have to retrieve the current project.

**Comment by emilienschultz** [comment]
Ok for the slug, and I don't want to make an API call to resolve the name. So I need to add a prop in the NavBar, I see. Thanks
