### ISSUE TITLE
Add a subnavbar for the process

### ISSUE THREAD

**Issue by emilienschultz** [emilienschultz/pyactivetigger#71]
@paulgirard What would you think for UX to add a secondary navbar for the project worflow, just under the current one (features/annotation/train/test)

This would allow to design a specific navbar for each kind of accounts in a second step (for the moment, we will do the full research workflow)

If ok, I could try to mimic the current navbar to do so.

**Comment by paulgirard** [comment]
I understand the idea.
You can have a look at bootstrap examples here : https://getbootstrap.com/docs/5.3/examples/headers/

I think I would personally prefer to use only one bar but to activate/show project related pages when on project page with a different style. I am not sure about that this being said. 

Do a first version as you think it's best and you'll see.
